#!/usr/bin/env bash

CURRENT_DIR=`pwd`
#rm ./build -rf
#mkdir build
cd ./build/
#cmake ../
ulimit -c unlimited
rm /test/cpp/erizo_cpp/bin/core -f 
make 
make install
cd ${CURRENT_DIR}
cp ./log4cxx.properties ./bin
cp ./config.json ./bin
cd ./bin
./erizo_agent_cpp
cd ${CURRENT_DIR}
